#!/bin/bash
#swapfile creation script:

# Environment variables:
  location="$2"
  size="$3"

# Function:

  # Create Swapfile
  create()
  {
  sudo dd if=/dev/zero of=$location bs=1 count=0 seek=$size

  sudo chmod 0600 $location

  sudo mkswap $location

  sudo swapon $location

  echo "$location none            swap    sw              0       0" | sudo tee --append /etc/fstab

  echo "vm.swappiness=100" | sudo tee --append /etc/sysctl.conf

  sudo sysctl -p

  sudo swapon -s

  free -m

  echo -e  "\n DONE"
  }

  # Delete Swapfile.
  delete()
  {
  sudo swapoff $location

  sudo sed --in-place '/swap/d' /etc/fstab

  sudo rm -rf $location

  sudo sed --in-place '/swappiness/d' /etc/sysctl.conf

  free -m

  echo -e  "\n DONE"
  }

  # Print Help.
  help()
  {
  cat <<EOF
  +---------------------+
  +  Swapfile Utility:  +
  +---------------------+

  create: ./swapfilec create /swap 1G
  delete: ./swapfilec delete /swap
  help:   ./swapfilec help
EOF
  }

# If no commandline argument is passed then print help.
if [[ -z $1 ]]
then
  help
else
  $1
fi
